name: live ssh deployment

on:
  push:
    branches: [ "main" ]

jobs:
  run-tests:
    name: Deploy
    runs-on: alpine:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      shell: sh
      run: apk add zip bash findutils

    - name: Test compression + RAM
      shell: sh
      run: ./src/tests/filesystem-ram.sh
