name: live ssh deployment

on:
  push:
    branches: [ "main" ]

jobs:
  run-tests:
    name: Test compressions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test compression + RAM
      shell: sh
      run: ./src/tests/filesystem-ram.sh
