name: live ssh deployment

on:
  push:
    branches: [ "main", "github-workflows" ]

jobs:
  run-tests:
    name: Test compressions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: echo "RUN apk add coreutils" > Dockerfile && docker build -t test-image .

    - name: Test compression
      run: |
        docker run --rm -v $(pwd):/app test-image sh -c "cd /app/src/tests && ./github-runner.sh"
